language: android
android:
  components:
    - build-tools-28
#    - build-tools-19
#    - build-tools-21
#    - build-tools-23
#    - build-tools-24
#    - build-tools-26
    - android-28
#    - android-19
#    - android-21
#    - android-23
#    - android-24
#    - android-26
before_install:
  - yes | sdkmanager --licenses
script:
   - chmod +x gradlew
   - ./gradlew build
   - cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/msg-share-app.apk
deploy:
  provider: releases
  api_key:
    secure: $API_TOKEN
  file:
    - app/build/outputs/apk/release/app-release-unsigned.apk
    - app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
