language: android
android:
  components:
    - tools
    - build-tools-28.0.2
    - android-19
#before_install:
#  - yes | sdkmanager "platforms;android-28"
script:
   - chmod +x gradlew
   - ./gradlew build
   - cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/msg-share-app.apk
deploy:
  provider: releases
  api_key:
    secure: $API_TOKEN
  file: app/build/outputs/apk/release/msg-share-app.apk
  skip_cleanup: true
  on:
    tags: true
