language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.2
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - chmod +x gradlew
   - ./gradlew build
   - cd app
   - cd build
   - cd outputs
   - cd apk
   - cd release
   - ls
deploy:
  provider: releases
  api_key:
    secure: $API_TOKEN
  file: app/build/outputs/apk/release/test.apk
  skip_cleanup: true
  on:
    tags: true
