language: android
android:
  components:
    - build-tools-28.0.2
    - android-28
script:
   - chmod +x gradlew
   - ./gradlew build
deploy:
  provider: releases
  api_key:
    secure: $API_TOKEN
  file:
    - app/build/outputs/apk/release/app-release-unsigned.apk
    - app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    tags: true
